server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/conectarecicla?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # crea/actualiza tablas automáticamente
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

# Configuración JWT
security:
  jwt:
    secret-key: "EstaEsUnaLlaveSuperSecretaParaJWT123456789"
    expiration: 3600000 # 1 hora (en milisegundos)

# Logs más legibles
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
