server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/conectarecicla?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret-key: bXktc2VjcmV0LWtleS1mb3Itand0LWV4YW1wbGUtYXBwbGljYXRpb24=
    expiration: 1200000
    refresh-threshold: 240000
